#Samuel hemma
- action:
  - data:
      event: Samuel_hemma
      value1: sensor.ar_bea_hemma
    service: ifttt.trigger
  alias: Samuel kommer hem
  id: '1502188318855'
  trigger:
  - entity_id: device_tracker.samuel_nexus6p
    from: 'not_home'
    platform: state
    to: 'home'
#Ingen hemma    
- action:
  - data:
      event: Ingen_hemma
    service: ifttt.trigger
  alias: Nibe ingen hemma set away
  id: '1502188650100'
  trigger:
  - entity_id: group.tracker
    from: 'home'
    platform: state
    to: 'not_home'
#Någon hemma    
- action:
  - data:
      event: Nagon_hemma
    service: ifttt.trigger
  alias: Nibe hemma set home mode
  id: '1502188791669'
  trigger:
  - entity_id: group.tracker
    from: 'not_home'
    platform: state
    to: 'home'
