- id: '1502188318855'
  alias: Samuel kommer hem
  action:
  - data_template:
      title: Samuels whereabouts
      target: email/samuel.tornberg@gmail.com
      message: '{{ states.sensor.ar_samuel_hemma.state }}'
    service: notify.pushbullet
  - data_template:
      title: Samuels whereabouts
      message: '{{ states.sensor.ar_samuel_hemma.state }}'
    service: notify.html5
  trigger:
  - entity_id: device_tracker.samuel_nexus6p
    from: not_home
    platform: state
    to: home
- id: '1502188650100'
  alias: Nibe ingen hemma set away
  action:
  - data:
      event: Ingen_hemma
    service: ifttt.trigger
  trigger:
  - entity_id: group.tracker
    from: home
    platform: state
    to: not_home
- id: '1502188791669'
  alias: Nibe hemma set home mode
  action:
  - data:
      event: Nagon_hemma
    service: ifttt.trigger
  trigger:
  - entity_id: group.tracker
    from: not_home
    platform: state
    to: home
- id: '1502794233544'
  alias: Bea kommer hem
  action:
  - data_template:
      title: Beas whereabouts
      target: email/samuel.tornberg@gmail.com
      message: '{{ states.sensor.ar_bea_hemma.state }}'
    service: notify.pushbullet
  - data_template:
      title: Beas whereabouts
      message: '{{ states.sensor.ar_bea_hemma.state }}'
    service: notify.html5
  trigger:
  - platform: state
    entity_id: device_tracker.beasiphone
    from: not_home
    to: home
- action:
  - data: {}
    service: notify.html5
  alias: Face detect samuel
  condition: []
  id: '1502845317455'
  trigger:
  - event_data:
      entity_id: camera.ip_webcam
      state: Samuel
    event_type: image_processing.msfaceidentify
    platform: event
