homeassistant:
  # Name of the location where Home Assistant is running
  name: Hemma
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elev
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml
  #   customize_glob: !include customize_glob.yaml
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret api_password
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - !secret trustednet


# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret ip_baseurl
  use_x_forwarded_for: true
  trusted_proxies: !secret ip_trustedproxy

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
#history:

# View all events in a logbook
logbook:

# Recorder?
recorder:
  purge_keep_days: 1
  purge_interval: 1

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    cache: True
    cache_dir: tts
    language: sv
    time_memory: 300

# Cloud
cloud:
  google_actions:
    filter:
      include_domains:
        - switch
        - light
        - climate

#group: !include groups.yaml
#automation: !include automations.yaml
#script: !include scripts.yaml

# Includes
scene: !include_dir_list scenes/
group: !include groups.yaml
automation: !include_dir_merge_list automations/
sensor: !include_dir_merge_list sensors/
device_tracker: !include device_trackers.yaml
script: !include_dir_merge_named scripts/
media_player: !include media_players.yaml
notify: !include notifies.yaml
switch: !include switches.yaml
zone: !include_dir_list zones/
intent_script: !include_dir_merge_named intent_scripts/

#IFTTT
ifttt:
  key: !secret ifttt_key

zwave:
  usb_path: /dev/ttyS2
  network_key: !secret zwave_networkkey
  autoheal: false

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

panel_iframe:
  googlecalendar:
    title: Familjens kalender
    url: !secret googlecalendarurl

#google_assistant:
#  project_id: someproject-2d0b8
#  client_id: !secret ga_client_id
#  access_token: !secret ga_access_token
#  exposed_domains:
#    - switch
#    - light
#    - group

#Homekit
homekit:
  auto_start: False
  filter:
    include_domains:
      - alarm_control_panel
      - light
#    exclude_entities:
#      - light.kitchen_light
