- platform: template
  sensors:
    template_calendar_samuel:
      value_template: >
        {{ strptime(states.calendar.samuelsaktiviteter.attributes.start_time, "%Y-%m-%d %H:%M:%S") }}
        {{ states.calendar.samuelsaktiviteter.attributes.message }}
      friendly_name: Samuels nästa aktivitet
      unit_of_measurement: ''

- platform: template
  sensors:
    template_calendar_beatrice:
      value_template: >
        {{ strptime(states.calendar.beatricesaktiviteter.attributes.start_time, "%Y-%m-%d %H:%M:%S") }}
        {{ states.calendar.beatricesaktiviteter.attributes.message }}
      friendly_name: Beatrice nästa aktivitet
      unit_of_measurement: ''

- platform: template
  sensors:
    template_calendar_john:
      value_template: >
        {{ strptime(states.calendar.johnsaktiviteter.attributes.start_time, "%Y-%m-%d %H:%M:%S") }}
        {{ states.calendar.johnsaktiviteter.attributes.message }}
      friendly_name: Johns nästa aktivitet
      unit_of_measurement: ''

- platform: template
  sensors:
    template_calendar_louise:
      value_template: >
        {{ strptime(states.calendar.louisesaktiviteter.attributes.start_time, "%Y-%m-%d %H:%M:%S") }}
        {{ states.calendar.louisesaktiviteter.attributes.message }}
      friendly_name: Louise nästa aktivitet
      unit_of_measurement: ''

- platform: template
  sensors:
    template_calendar_elsa:
      value_template: >
        {{ strptime(states.calendar.elsasaktiviteter.attributes.start_time, "%Y-%m-%d %H:%M:%S") }}
        {{ states.calendar.elsasaktiviteter.attributes.message }}
      friendly_name: Elsas nästa aktivitet
      unit_of_measurement: ''

- platform: template
  sensors:
    template_calendar_gabriel:
      value_template: >
        {% if is_state("states.calendar.gabrielsaktiviteter.attributes.start_time", "null") %} Ingen händelse den närmaste tiden {% else %}
        {{ strptime(states.calendar.gabrielsaktiviteter.attributes.start_time, "%Y-%m-%d %H:%M:%S") }}
        {{ states.calendar.gabrielsaktiviteter.attributes.message }}
        {% endif %}
      friendly_name: Gabriels nästa aktivitet
      unit_of_measurement: ''

- platform: template
  sensors:
    template_calendar_tornberg:
      value_template: >
        {{ strptime(states.calendar.tornbergs.attributes.start_time, "%Y-%m-%d %H:%M:%S") }}
        {{ states.calendar.tornbergs.attributes.message }}
      friendly_name: Nästa aktivitet oavsett familjemedlem
      unit_of_measurement: ''
