- alias: "S채tt p책 lampa strax innan solen g책r ner"
  action:
    service: script.turn_on
    entity_id: script.varde_ljus
  id: '1334542788017'
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 1.5

- alias: "Mysbelysning @ nautical dawn"
  action:
    service: script.turn_on
    entity_id: script.mysbelysning
  id: '1222160338824'
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: -12

- alias: "St채ng av lampa senast mitt i natten"
  action:
    service: script.turn_on
    entity_id: script.godnatt
  id: '1405940706141'
  trigger:
  - platform: time
    at: '1:00'